device: null
#pretrained_model: ckpt/train/2024-08-20_04-34-49_Apf/t[01700]_r[316.39].pt
pretrained_model: null
ckpt_name: CnnElu

# collector
collector:
  total_frames: 3_000_000
  frames_per_batch: 10
  num_envs: 16
  eps_start: 1.0
  eps_end: 0.05
  annealing_frames: 1_000_000
  init_random_frames: 10_000
#  init_random_frames: 0

# buffer
buffer:
  buffer_size: 500_000
  batch_size: 1024

# Optim
optim:
  lr: 3.0e-4
  max_grad_norm: 40

# loss
loss:
  gamma: 0.99
  hard_update_freq: 400
  num_updates: 1

# logger
logger:
  backend: tensorboard
  model_name: DQN
  exp_name: Train
  test_interval: 50_000
#  test_interval: 20_000
  test_steps: 2_000
  video: True
